name: Container Base Image Release
concurrency: production
on:
  workflow_dispatch:
jobs:
  release-base-image:
    runs-on: ubuntu-latest
    name: Release base container image
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up qemu
        uses: docker/setup-qemu-action@v2

      - name: Set up docker buildx
        uses: docker/setup-buildx-action@v2
        with:
          platforms: linux/amd64,linux/arm64

      - name: Read metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/jikan-me/jikan-rest-php
            jikanme/jikan-rest-php
          tags: |
            type=sha
            type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', 'master') }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          context: ./docker/base_image/php-8.0
          # let's use github action cache storage
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            GITHUB_PERSONAL_TOKEN=${{ secrets.GITHUB_TOKEN }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
